# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import schema_pb2 as schema__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lc.proto',
  package='lc.schema',
  syntax='proto3',
  serialized_options=b'Z4github.com/vchain-us/ledger-compliance/server/schema',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08lc.proto\x12\tlc.schema\x1a\x0cschema.proto\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x0cTamperReport\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\x0c\n\x04root\x18\x03 \x01(\x0c\"f\n\rReportOptions\x12(\n\x07payload\x18\x01 \x01(\x0b\x32\x17.lc.schema.TamperReport\x12+\n\tsignature\x18\x02 \x01(\x0b\x32\x18.immudb.schema.Signature2\xc1\x03\n\tLcService\x12\x36\n\x03Set\x12\x17.immudb.schema.KeyValue\x1a\x14.immudb.schema.Index\"\x00\x12\x30\n\x03Get\x12\x12.immudb.schema.Key\x1a\x13.immudb.schema.Item\"\x00\x12@\n\x07SafeSet\x12\x1d.immudb.schema.SafeSetOptions\x1a\x14.immudb.schema.Proof\"\x00\x12\x43\n\x07SafeGet\x12\x1d.immudb.schema.SafeGetOptions\x1a\x17.immudb.schema.SafeItem\"\x00\x12<\n\x0b\x43urrentRoot\x12\x16.google.protobuf.Empty\x1a\x13.immudb.schema.Root\"\x00\x12\x41\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x1d.immudb.schema.HealthResponse\"\x00\x12\x42\n\x0cReportTamper\x12\x18.lc.schema.ReportOptions\x1a\x16.google.protobuf.Empty\"\x00\x42\x36Z4github.com/vchain-us/ledger-compliance/server/schemab\x06proto3'
  ,
  dependencies=[schema__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_TAMPERREPORT = _descriptor.Descriptor(
  name='TamperReport',
  full_name='lc.schema.TamperReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='lc.schema.TamperReport.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='lc.schema.TamperReport.key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root', full_name='lc.schema.TamperReport.root', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=122,
)


_REPORTOPTIONS = _descriptor.Descriptor(
  name='ReportOptions',
  full_name='lc.schema.ReportOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='lc.schema.ReportOptions.payload', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='lc.schema.ReportOptions.signature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=226,
)

_REPORTOPTIONS.fields_by_name['payload'].message_type = _TAMPERREPORT
_REPORTOPTIONS.fields_by_name['signature'].message_type = schema__pb2._SIGNATURE
DESCRIPTOR.message_types_by_name['TamperReport'] = _TAMPERREPORT
DESCRIPTOR.message_types_by_name['ReportOptions'] = _REPORTOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TamperReport = _reflection.GeneratedProtocolMessageType('TamperReport', (_message.Message,), {
  'DESCRIPTOR' : _TAMPERREPORT,
  '__module__' : 'lc_pb2'
  # @@protoc_insertion_point(class_scope:lc.schema.TamperReport)
  })
_sym_db.RegisterMessage(TamperReport)

ReportOptions = _reflection.GeneratedProtocolMessageType('ReportOptions', (_message.Message,), {
  'DESCRIPTOR' : _REPORTOPTIONS,
  '__module__' : 'lc_pb2'
  # @@protoc_insertion_point(class_scope:lc.schema.ReportOptions)
  })
_sym_db.RegisterMessage(ReportOptions)


DESCRIPTOR._options = None

_LCSERVICE = _descriptor.ServiceDescriptor(
  name='LcService',
  full_name='lc.schema.LcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=229,
  serialized_end=678,
  methods=[
  _descriptor.MethodDescriptor(
    name='Set',
    full_name='lc.schema.LcService.Set',
    index=0,
    containing_service=None,
    input_type=schema__pb2._KEYVALUE,
    output_type=schema__pb2._INDEX,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='lc.schema.LcService.Get',
    index=1,
    containing_service=None,
    input_type=schema__pb2._KEY,
    output_type=schema__pb2._ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SafeSet',
    full_name='lc.schema.LcService.SafeSet',
    index=2,
    containing_service=None,
    input_type=schema__pb2._SAFESETOPTIONS,
    output_type=schema__pb2._PROOF,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SafeGet',
    full_name='lc.schema.LcService.SafeGet',
    index=3,
    containing_service=None,
    input_type=schema__pb2._SAFEGETOPTIONS,
    output_type=schema__pb2._SAFEITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CurrentRoot',
    full_name='lc.schema.LcService.CurrentRoot',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=schema__pb2._ROOT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Health',
    full_name='lc.schema.LcService.Health',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=schema__pb2._HEALTHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReportTamper',
    full_name='lc.schema.LcService.ReportTamper',
    index=6,
    containing_service=None,
    input_type=_REPORTOPTIONS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LCSERVICE)

DESCRIPTOR.services_by_name['LcService'] = _LCSERVICE

# @@protoc_insertion_point(module_scope)
