name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: actions/checkout@v1
      - name: Init
        working-directory: ./src
        run: make init
      - name: Dev init
        working-directory: ./src
        run: make dev
      - name: Test
        working-directory: ./src
        run: make test
      - name: Install
        working-directory: ./src
        run: make install
